name: WakaTime Status

on:
  schedule:
    # Runs at 12:00 AM UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stat
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE_COLORS: "True"
